version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
    depends_on:
      - database
    networks:
      - app_network
  database:
    platform: linux/amd64
    image: postgres
    container_name: turborepo_postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - app_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
